version: '0.1'

services:
  dashboard:
    container_name: dashboard
    hostname: dashboard
    image: oss-know/dashboard:latest
    restart: always
    # 跨多个Docker-compose配置文件，services在一个网桥
    networks:
      - dev-network
    ports:
      - "8081:8081"


networks:
  overlay-network:
    driver: overlay
    external: true
  dev-network:
    external: true
